### ISSUE TITLE
Error when opening Installed version

### ISSUE THREAD

**Issue by FloThinksPi** [Biswa96/WSLInstall#1]
I installed like in the Readme.md
Set the default with `wlsconfig.exe /s Fedora`
but got 
```
C:\Fedora>bash
Error: 0x80070002
Press any key to continue...
```
When executing bash. Any Ideas ? `rootf` got unpacked correctly. Also when running bash, the folder `tmp` gets created.

**Comment by Biswa96** [comment]
Run WSL.exe instead of bas.exe

**Comment by FloThinksPi** [comment]
@Biswa96 Thanks for your help but i still have that issue with Fedoras Docker image aswell as a Ubuntu image. Strange. WsInstall works, wslconfig shows the Disto and i can set it to standart with `wslconfig.exe /s Fedora` but then i get above error when running `WLS.exe` or `bash`.

Is this rootfs tree valid ? The rootfs folder got created by WsInstall.
```
rootfs/
├── 4ec43240cac37d1668dde410ae5f1457e2703ce4e666d687ac811aa29510a875.json
├── ba797a5a4d659ab244b91045eff16e1e1f051295240b388174959ffec63f028a
│   ├── json
│   ├── layer.tar
│   └── VERSION
├── manifest.json
└── repositories
```

**Comment by Biswa96** [comment]
See this wiki page: https://github.com/DDoSolitary/LxRunOffline/wiki where I wrote the detailed process. And yes the rootfs tree is valid. In short, extract the layer.tar in a folder and then re-compressed the extracted files in .tar.gz file.

**Comment by FloThinksPi** [comment]
Jup with the new instructions the rootfs gets propperly unpacked and used. Thanks 👍  😃

**Comment by Biswa96** [comment]
Thanks for your collaboration. If there is any information missing or have to be added, please inform. BTW, this is the first issue in my repo. And I'm glad to solve your issue. 😇
